sudo: false
dist: trusty

language: c

addons:
  apt:
    packages:
      - liblzma-dev

before_script:
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure && make && make check
